server:
  port: 8080
  address: 0.0.0.0
  servlet:
    session:
      cookie:
        name: LIBRARY_SESSION
        http-only: true
        same-site: lax
      timeout: 2h

spring:
  application:
    name: library-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL:jdbc:mysql://localhost:3306/db_library?serverTimezone=Asia/Seoul&characterEncoding=UTF-8}
    username: ${DB_USERNAME:user_library}
    password: ${DB_PASSWORD:1234}
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: update
      format_sql: true
